import { createContext, useContext, useState } from 'react';
import * as OpenCC from 'opencc-js';

const TW_OVERRIDES = [
  ['服務器', '伺服器'],
  ['軟件', '軟體'],
  ['地鐵', '捷運'],
];

let _toTW = null;
function toTW(str) {
  if (!_toTW) _toTW = OpenCC.Converter({ from: 'cn', to: 'tw' });
  let result = _toTW(str);
  for (const [from, to] of TW_OVERRIDES) result = result.replaceAll(from, to);
  return result;
}

const T = {
  //english
  en: {
    appName: 'Prague Stories',
    'nav.explore': 'Explore',
    'nav.map': 'Map',
    'nav.guide': 'Guide',
    'nav.randomDraw': 'Draw',
    'nav.dashboard': 'Dashboard',
    'nav.history': 'History',
    'nav.logout': 'Logout',
    'explore.title': 'Explore Prague and Bohemia',
    'explore.titleGuest': 'Login to Explore Prague!',
    'explore.statsLabel': 'location cards collected',
    'explore.addLocation': '+ Add Location',
    'grid.searchPlaceholder': 'Search locations...',
    'grid.filterAll': 'All',
    'grid.filterDiscovered': 'My Collections',
    'grid.filterLabels': 'Labels',
    'grid.filterRarity': 'Rarity',
    'grid.clearLabels': 'Clear',
    'grid.showing': 'showing',
    'grid.noResults': 'No locations found.',
    'grid.sortDistance': 'Distance',
    'grid.sortNewest': 'Newest',
    'grid.sortRarity': 'Top Rarity',
    'grid.sortCheckin': 'Recently Collected',
    'label.historical': 'Historical',
    'label.modern': 'Modern',
    'label.cultural': 'Cultural & Art',
    'label.museum': 'Museum',
    'label.monument': 'Monument & Statue',
    'label.communism': 'Communism (Brutalism)',
    'label.church': 'Church & Cathedral',
    'label.bridge': 'Bridge',
    'label.academy': 'Academy',
    'label.architecture': 'Architecture',
    'label.landmark': 'Landmark',
    'label.palace': 'Palace',
    'label.villa': 'Villa',
    'label.basilica': 'Basilica',
    'label.monastery': 'Monastery',
    'label.village-and-town': 'Village & Town',
    'label.park': 'Park & Garden',
    'label.nature': 'Nature and Landscape',
    'label.restaurants-and-cafes': 'Restaurants and cafes',
    'label.cafe': 'Cafe & Restaurant',
    'label.hidden-gem': 'Hidden Gem',
    'label.square': 'Square',
    'label.transport': 'Transport',
    'label.tower': 'Tower',
    'label.street': 'Street & Neighbourhood',
    'label.municipal': 'Municipal',
    'label.factory': 'Industrial',
    'label.embassy': 'Embassy',
    'label.ruin': 'Ruin',
    'label.jewish': 'Jewish',
    'label.waterbody': 'Waterbody',
    'label.geology': 'Geography',
    'label.homestead': 'Homestead',
    'dashboard.title': 'Explorer Dashboard',
    'dashboard.titleGuest': 'Log in to use the Explorer Dashboard and begin your Prague journey',
    'dashboard.xpToNext': 'XP to next level',
    'dashboard.locations': 'Locations',
    'dashboard.ofPreset': 'of {n} location cards',
    'dashboard.totalVisits': 'collected',
    'dashboard.categoryBreakdown': 'Category Breakdown',
    'dashboard.rarityBreakdown': 'Rarity Breakdown',
    'dashboard.totalXP': 'Total XP',
    'dashboard.achievements': 'Achievements',
    'dashboard.explorerLevels': 'Explorer Levels',
    'dashboard.wakeLockEnable': 'Keep Screen On',
    'dashboard.wakeLockActive': 'Screen Always On',
    'dashboard.wakeLockUnsupported': 'Wake lock not supported on this browser',
    'map.clickMarker': 'Click a marker to explore',
    'map.legend': '● Gold = unlocked  ·  ● Grey = locked',
    'common.loading': 'Loading...',
    'common.visited': '✓ COLLECTED',
    'common.noDesc': 'Description not yet available.',
    'common.wikipedia': '📖 Wikipedia',
    'common.googleMaps': '🗺 Navigate on Google Maps',
    'detail.added': 'Added',
    'detail.at': 'at',
    'detail.distanceAway': '{dist} away',
    'proximity.title': '★ Discovery!',
    'proximity.prompt': 'You found {name}! Collect now?',
    'levelUp.title': 'LEVEL UP!',
    'levelUp.newLevel': 'LEVEL {level}',
    'levelUp.subtitle': 'You are now a',
    'levelUp.continue': 'Continue',
    'notif.optInTitle': 'Enable location alerts?',
    'notif.optInBody': 'Get notified when you\'re within 100m of an undiscovered location.',
    'notif.optInEnable': 'Enable',
    'common.checkIn': '★ Collect',
    'common.locked': 'LOCKED',
    'common.cancel': 'Cancel',
    'add.title': 'Add Custom Location',
    'add.name': 'Name',
    'add.labels': 'Labels',
    'add.latitude': 'Latitude',
    'add.longitude': 'Longitude',
    'add.wikiUrl': 'Wikipedia URL (optional)',
    'add.description': 'Description (optional)',
    'add.coverPhoto': 'Cover Photo (optional)',
    'add.coverPhotoHint': 'JPG / PNG / WebP · max 1 MB',
    'add.adding': 'Adding...',
    'auth.login': 'Login',
    'auth.loginSubtitle': 'Welcome back, explorer',
    'auth.register': 'Register',
    'auth.registerSubtitle': 'Prague hides countless secrets. You know zero of them. Unacceptable.',
    'auth.registerFlavor': 'Create thy adventurer profile. The Golden City awaits.',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.username': 'Username',
    'auth.loggingIn': 'Logging in...',
    'auth.enterPrague': '▶ Enter Prague',
    'auth.noAccount': 'No account?',
    'auth.registerHere': 'Register here',
    'auth.creatingAccount': 'Creating account...',
    'auth.startExploring': '▶ Start Exploring',
    'auth.haveAccount': 'Have an account?',
    'auth.loginHere': 'Login here',
    'auth.continueAsGuest': 'Continue without login',
    'auth.loginToCollect': 'Log in to collect',
    'nav.login': 'Login',
    'draw.title': 'The Blind Draw',
    'draw.tagline': 'Too many pins on the map. Too little willpower to pick one. Let fate handle it.',
    'draw.challenge': 'Analysis paralysis is a real affliction, and this app cannot cure it — but it can bypass it entirely. One tap, one random undiscovered location, zero decisions required.',
    'draw.intro1': "This is a deck of every location in Prague you haven't found yet, shuffled and offered to you face-down. Once every 24 hours, you may draw one card. What you get is what you get — refusing to go is allowed, but so is quietly regretting it.",
    'draw.intro2': 'Locations drawn this way pay triple XP if you actually show up and collect them before the offer expires. The app rewards decisiveness — mostly because it feels bad watching people scroll the Explore grid for half an hour.',
    'draw.rulesTitle': 'The Rules',
    'draw.rule1': "Press the button. One location, chosen at random from everywhere you haven't been, is revealed.",
    'draw.rule2': 'You get 24 hours to go there and collect it. The XP for that one visit is tripled.',
    'draw.rule3': 'Whether you go or not, the card flips back to ??? after 24 hours, and a new draw becomes available.',
    'draw.rule4': 'No re-rolls. No peeking at the next one early. That would defeat the point of the exercise entirely.',
    'draw.mysteryHint': 'Somewhere in Prague. Unnamed. Undiscovered. Waiting to be dealt.',
    'draw.buttonDraw': 'Draw a Location',
    'draw.buttonDrawing': 'Shuffling the deck...',
    'draw.bonusTag': '3× XP if collected in time',
    'draw.revealedHintPre': 'The die is cast. Go ',
    'draw.revealedHintLink': 'explore',
    'draw.revealedHintPost': '.',
    'draw.viewButton': 'View Card',
    'draw.cooldownLabel': 'Next draw in',
    'draw.noneLeftTitle': "Deck's Empty",
    'draw.noneLeft': "You've already found everywhere in Prague this app knows about. There is nothing left to draw. Genuinely impressive, and also slightly concerning.",
    'draw.alreadyCollected': '✓ Bonus Claimed',
    'draw.guestTrialNote': "You're trying this out as a guest — this draw won't be saved. Log in if you actually want to collect XP for it.",
    'detail.bonusApplied': '🎲 3× Random Draw Bonus!',
    'history.title': 'History Timeline',
    'history.tagline': "From a prophecy on a cliff to a nation's founding — drag through Prague's history and see where it actually happened.",
    'history.dragHint': 'Browse the eras on the left to travel through time',
    'history.comingSoon': 'This era is still being written. Check back soon.',
    'history.relatedLandmarksLabel': 'See it for yourself',
  },
  //czech
  cz: {
    appName: 'Pražské Příběhy',
    'nav.explore': 'Průzkum',
    'nav.map': 'Mapa',
    'nav.guide': 'Průvodce',
    'nav.randomDraw': 'Los',
    'nav.dashboard': 'Přehled',
    'nav.history': 'Historie',
    'nav.logout': 'Odhlásit',
    'explore.title': 'Prozkoumej Prahu a Čechy',
    'explore.titleGuest': 'Přihlaste se a prozkoumejte Prahu!',
    'explore.statsLabel': 'míst sesbíráno',
    'explore.addLocation': '+ Přidat Místo',
    'grid.searchPlaceholder': 'Hledat místa...',
    'grid.filterAll': 'Vše',
    'grid.filterDiscovered': 'Moje sbírka',
    'grid.filterLabels': 'Štítky',
    'grid.filterRarity': 'Vzácnost',
    'grid.clearLabels': 'Smazat',
    'grid.showing': 'zobrazeno',
    'grid.noResults': 'Žádná místa nenalezena.',
    'grid.sortDistance': 'Vzdálenost',
    'grid.sortNewest': 'Nejnovější',
    'grid.sortRarity': 'Dle vzácnosti',
    'grid.sortCheckin': 'Naposledy navštíveno',
    'label.historical': 'Historické',
    'label.modern': 'Moderní',
    'label.cultural': 'Kultura & Umění',
    'label.museum': 'Muzeum',
    'label.monument': 'Pomník & Socha',
    'label.communism': 'Komunismus',
    'label.church': 'Kostel',
    'label.bridge': 'Most',
    'label.academy': 'Akademie',
    'label.architecture': 'Architektura',
    'label.landmark': 'Dominanta',
    'label.palace': 'Palác',
    'label.villa': 'Vila',
    'label.basilica': 'Bazilika',
    'label.monastery': 'Klášter',
    'label.village-and-town': 'Vesnice & Město',
    'label.park': 'Park & Zahrada',
    'label.nature': 'Příroda a krajina',
    'label.restaurants-and-cafes': 'Restaurace a kavárny',
    'label.cafe': 'Kavárna',
    'label.hidden-gem': 'Skrytý klenot',
    'label.square': 'Náměstí',
    'label.transport': 'Doprava',
    'label.tower': 'Věž',
    'label.street': 'Ulice & Čtvrť',
    'label.municipal': 'Obecní',
    'label.factory': 'Průmysl',
    'label.embassy': 'Velvyslanectví',
    'label.ruin': 'Zřícenina',
    'label.jewish': 'Židovské',
    'label.waterbody': 'Vodní plocha',
    'label.geology': 'Geografie',
    'label.homestead': 'Usedlost',
    'dashboard.title': 'Průzkumník',
    'dashboard.titleGuest': 'Přihlaste se a odemkněte Průzkumníkův přehled, abyste zahájili cestu Prahou',
    'dashboard.xpToNext': 'XP do další úrovně',
    'dashboard.locations': 'Místa',
    'dashboard.ofPreset': 'z {n} přednastavených',
    'dashboard.totalVisits': 'sesbíráno',
    'dashboard.categoryBreakdown': 'Kategorie',
    'dashboard.rarityBreakdown': 'Vzácnost',
    'dashboard.totalXP': 'Celkem XP',
    'dashboard.achievements': 'Úspěchy',
    'dashboard.explorerLevels': 'Úrovně Průzkumníka',
    'dashboard.wakeLockEnable': 'Ponechat obrazovku zapnutou',
    'dashboard.wakeLockActive': 'Obrazovka stále svítí',
    'dashboard.wakeLockUnsupported': 'Tento prohlížeč nepodporuje blokování uspání',
    'map.clickMarker': 'Klikni na značku pro průzkum',
    'map.legend': '● Zlatá = navštíveno  ·  ● Šedá = zamčeno',
    'common.loading': 'Načítám...',
    'common.visited': '✓ SESBÍRÁNO',
    'common.noDesc': 'Popis zatím není k dispozici.',
    'common.wikipedia': '📖 Wikipedie',
    'common.googleMaps': '🗺 Navigace v Mapách Google',
    'detail.added': 'Přidáno',
    'detail.at': 'dne',
    'detail.distanceAway': '{dist} daleko',
    'proximity.title': '★ Objev!',
    'proximity.prompt': 'Našel jsi {name}! Sbírat nyní?',
    'levelUp.title': 'POSTUP NA ÚROVEŇ!',
    'levelUp.newLevel': 'ÚROVEŇ {level}',
    'levelUp.subtitle': 'Nyní jsi',
    'levelUp.continue': 'Pokračovat',
    'notif.optInTitle': 'Povolit upozornění na polohu?',
    'notif.optInBody': 'Dostávej upozornění, když jsi do 100 m od neobjeveného místa.',
    'notif.optInEnable': 'Povolit',
    'common.checkIn': '★ Sbírat',
    'common.locked': 'UZAMČENO',
    'common.cancel': 'Zrušit',
    'add.title': 'Přidat vlastní místo',
    'add.name': 'Název',
    'add.labels': 'Štítky',
    'add.latitude': 'Zeměpisná šířka',
    'add.longitude': 'Zeměpisná délka',
    'add.wikiUrl': 'Wikipedia URL (volitelné)',
    'add.description': 'Popis (volitelné)',
    'add.coverPhoto': 'Fotografie (volitelné)',
    'add.coverPhotoHint': 'JPG / PNG / WebP · max 1 MB',
    'add.adding': 'Přidávám...',
    'auth.login': 'Přihlášení',
    'auth.loginSubtitle': 'Vítej zpět, průzkumníku',
    'auth.register': 'Registrace',
    'auth.registerSubtitle': 'Praha ukrývá bezpočet tajemství. Neznáš ani jedno. Nepřijatelné.',
    'auth.registerFlavor': 'Vytvoř si profil dobroduha. Zlaté Město čeká.',
    'auth.email': 'E-mail',
    'auth.password': 'Heslo',
    'auth.username': 'Uživatelské jméno',
    'auth.loggingIn': 'Přihlašuji...',
    'auth.enterPrague': '▶ Vstoupit do Prahy',
    'auth.noAccount': 'Nemáš účet?',
    'auth.registerHere': 'Zaregistruj se',
    'auth.creatingAccount': 'Vytvářím účet...',
    'auth.startExploring': '▶ Začít Prozkoumávat',
    'auth.haveAccount': 'Máš účet?',
    'auth.loginHere': 'Přihlásit se zde',
    'auth.continueAsGuest': 'Pokračovat bez přihlášení',
    'auth.loginToCollect': 'Přihlaste se pro sbírání',
    'nav.login': 'Přihlásit',
    'draw.title': 'Slepý los',
    'draw.tagline': 'Příliš mnoho pinů na mapě. Příliš málo vůle vybrat si jeden. Nech to na osudu.',
    'draw.challenge': 'Ochromující rozhodování je skutečná nemoc a tahle aplikace ji neumí vyléčit — ale umí ji úplně obejít. Jedno klepnutí, jedno náhodné nenavštívené místo, žádná rozhodnutí nejsou potřeba.',
    'draw.intro1': 'Tohle je balíček všech míst v Praze, která jsi ještě nenašel, zamíchaný a nabídnutý lícem dolů. Jednou za 24 hodin si smíš vytáhnout jednu kartu. Co padne, to padne — odmítnout jít je povoleno, stejně jako toho tiše litovat.',
    'draw.intro2': 'Místa vytažená tímto způsobem vyplácí trojnásobné XP, pokud se tam skutečně dostavíš a sesbíráš je, než nabídka vyprší. Aplikace odměňuje rozhodnost — hlavně proto, že je nepříjemné sledovat, jak lidé půl hodiny scrolují v Průzkumu.',
    'draw.rulesTitle': 'Pravidla',
    'draw.rule1': 'Stiskni tlačítko. Odhalí se jedno náhodně vybrané místo ze všech, kde jsi ještě nebyl.',
    'draw.rule2': 'Máš 24 hodin na to, abys tam došel a sesbíral ho. XP za tuto jednu návštěvu je ztrojnásobené.',
    'draw.rule3': 'Ať už tam dojdeš nebo ne, karta se po 24 hodinách otočí zpět na ??? a stane se dostupným nový los.',
    'draw.rule4': 'Žádné nové losování. Žádné nakukování dopředu. To by zcela popřelo smysl celého cvičení.',
    'draw.mysteryHint': 'Někde v Praze. Beze jména. Neobjevené. Čeká, až bude rozdáno.',
    'draw.buttonDraw': 'Vytáhnout místo',
    'draw.buttonDrawing': 'Míchám balíček...',
    'draw.bonusTag': '3× XP, pokud sesbíráno včas',
    'draw.revealedHintPre': 'Kostky jsou vrženy. Jdi to ',
    'draw.revealedHintLink': 'prozkoumat',
    'draw.revealedHintPost': '.',
    'draw.viewButton': 'Zobrazit kartu',
    'draw.cooldownLabel': 'Další los za',
    'draw.noneLeftTitle': 'Balíček je prázdný',
    'draw.noneLeft': 'Už jsi našel všechna místa v Praze, o kterých tahle aplikace ví. Není co losovat. Upřímně, obdivuhodné, a trochu znepokojivé.',
    'draw.alreadyCollected': '✓ Bonus vybrán',
    'draw.guestTrialNote': 'Tohle zkoušíš jako host — tenhle los se nikam neuloží. Pokud za něj chceš opravdu sbírat XP, přihlas se.',
    'detail.bonusApplied': '🎲 3× Bonus ze slepého losu!',
    'history.title': 'Osa dějin',
    'history.tagline': 'Od proroctví na skále po vznik národa — projeďte se dějinami Prahy a podívejte se, kde se to všechno doopravdy odehrálo.',
    'history.dragHint': 'Procházejte éry vlevo a cestujte časem',
    'history.comingSoon': 'Tahle éra se ještě píše. Zkuste to znovu brzy.',
    'history.relatedLandmarksLabel': 'Podívejte se tam sami',
  },
  //chinese
  zh: {
    appName: '布拉格故事',
    'nav.explore': '探索',
    'nav.map': '地图',
    'nav.guide': '攻略',
    'nav.randomDraw': '抽签',
    'nav.dashboard': '仪表盘',
    'nav.history': '城史',
    'nav.logout': '退出',
    'explore.title': '探索布拉格与波希米亚',
    'explore.titleGuest': '登录以探索布拉格！',
    'explore.statsLabel': '个地点卡片已收集',
    'explore.addLocation': '+ 添加地点',
    'grid.searchPlaceholder': '搜索地点...',
    'grid.filterAll': '全部',
    'grid.filterDiscovered': '我的收藏',
    'grid.filterLabels': '标签',
    'grid.filterRarity': '稀有度',
    'grid.clearLabels': '清除',
    'grid.showing': '显示',
    'grid.noResults': '未找到任何地点。',
    'grid.sortDistance': '距离',
    'grid.sortNewest': '最新',
    'grid.sortRarity': '高稀有度',
    'grid.sortCheckin': '最近收藏',
    'label.historical': '历史',
    'label.modern': '现代',
    'label.cultural': '文化与艺术',
    'label.museum': '博物馆',
    'label.monument': '纪念碑与雕像',
    'label.communism': '共产主义',
    'label.church': '教堂',
    'label.bridge': '桥梁',
    'label.academy': '学术',
    'label.architecture': '建筑',
    'label.landmark': '地标',
    'label.palace': '宫殿',
    'label.villa': '别墅',
    'label.basilica': '宗座圣殿',
    'label.monastery': '修道院',
    'label.village-and-town': '村庄与城镇',
    'label.park': '公园与花园',
    'label.nature': '自然与风景',
    'label.restaurants-and-cafes': '餐厅与咖啡馆',
    'label.cafe': '咖啡馆',
    'label.hidden-gem': '隐藏景点',
    'label.square': '广场',
    'label.transport': '交通',
    'label.tower': '塔楼',
    'label.street': '街区',
    'label.municipal': '市政',
    'label.factory': '工业',
    'label.embassy': '大使馆',
    'label.ruin': '遗迹',
    'label.jewish': '犹太',
    'label.waterbody': '水体',
    'label.geology': '地理',
    'label.homestead': '庄园',
    'dashboard.title': '探索者仪表盘',
    'dashboard.titleGuest': '登录后使用探索者仪表盘，开启你的布拉格之旅',
    'dashboard.xpToNext': 'XP 到下一级',
    'dashboard.locations': '地点',
    'dashboard.ofPreset': '共 {n} 个地点卡片',
    'dashboard.totalVisits': '次收集',
    'dashboard.categoryBreakdown': '分类统计',
    'dashboard.rarityBreakdown': '稀有度统计',
    'dashboard.totalXP': '总经验值',
    'dashboard.achievements': '成就',
    'dashboard.explorerLevels': '探索者等级',
    'dashboard.wakeLockEnable': '保持屏幕常亮',
    'dashboard.wakeLockActive': '屏幕常亮中',
    'dashboard.wakeLockUnsupported': '此浏览器不支持屏幕唤醒锁',
    'map.clickMarker': '点击标记探索地点',
    'map.legend': '● 金色 = 已解锁  ·  ● 灰色 = 已锁定',
    'common.loading': '加载中...',
    'common.visited': '✓ 已收藏',
    'common.noDesc': '暂无描述。',
    'common.wikipedia': '📖 维基百科',
    'common.googleMaps': '🗺 在Google地图上导航',
    'detail.added': '添加',
    'detail.at': '于',
    'detail.distanceAway': '距离 {dist}',
    'proximity.title': '★ 发现！',
    'proximity.prompt': '你发现了{name}！现在收藏？',
    'levelUp.title': '升级了！',
    'levelUp.newLevel': '等级 {level}',
    'levelUp.subtitle': '你现在是',
    'levelUp.continue': '继续',
    'notif.optInTitle': '启用位置提醒？',
    'notif.optInBody': '当你距离未发现的地点100米内时收到通知。',
    'notif.optInEnable': '启用',
    'common.checkIn': '★ 打卡',
    'common.locked': '已锁定',
    'common.cancel': '取消',
    'add.title': '添加自定义地点',
    'add.name': '名称',
    'add.labels': '标签',
    'add.latitude': '纬度',
    'add.longitude': '经度',
    'add.wikiUrl': '维基百科 URL（可选）',
    'add.description': '简介（可选）',
    'add.coverPhoto': '封面照片（可选）',
    'add.coverPhotoHint': 'JPG / PNG / WebP · 最大 1 MB',
    'add.adding': '添加中...',
    'auth.login': '登录',
    'auth.loginSubtitle': '欢迎回来，探索者',
    'auth.register': '注册',
    'auth.registerSubtitle': '布拉格藏着无数秘密，你一个都不知道。不可接受。',
    'auth.registerFlavor': '创建你的冒险者档案，黄金之城在等待你。',
    'auth.email': '邮箱',
    'auth.password': '密码',
    'auth.username': '用户名',
    'auth.loggingIn': '登录中...',
    'auth.enterPrague': '▶ 进入布拉格',
    'auth.noAccount': '还没有账号？',
    'auth.registerHere': '立即注册',
    'auth.creatingAccount': '创建账号中...',
    'auth.startExploring': '▶ 开始探索',
    'auth.haveAccount': '已有账号？',
    'auth.loginHere': '立即登录',
    'auth.continueAsGuest': '不登录继续浏览',
    'auth.loginToCollect': '登录后收藏',
    'nav.login': '登录',
    'draw.title': '盲抽',
    'draw.tagline': '地图上钉子太多，选择困难症发作。不如交给命运决定。',
    'draw.challenge': '选择困难症是种真实存在的毛病，这个应用治不好它——但可以完全绕过它。点一下，随机抽出一个你还没发现的地点，无需做任何决定。',
    'draw.intro1': '把布拉格所有你还没找到的地点想象成一副牌，洗好后扣在桌上递给你。每24小时，你可以抽一张。抽到什么就是什么——你可以选择不去，但也只能默默后悔。',
    'draw.intro2': '以这种方式抽到的地点，只要你真的赶在期限内前往打卡，就能获得三倍经验值。这个应用奖励果断——主要是因为看着人们在探索页面滚动半个小时实在有点难受。',
    'draw.rulesTitle': '游戏规则',
    'draw.rule1': '按下按钮。系统会从你还没去过的所有地点里随机揭晓一个。',
    'draw.rule2': '你有24小时前往并完成打卡。这次打卡的经验值将翻三倍。',
    'draw.rule3': '无论你去不去，24小时后卡片都会自动翻回「？？？」，新的一次抽取随即开放。',
    'draw.rule4': '不能重抽，也不能提前偷看下一个。那样就完全违背了这个玩法的初衷。',
    'draw.mysteryHint': '在布拉格的某处。无名。未被发现。等待被揭晓。',
    'draw.buttonDraw': '抽取地点',
    'draw.buttonDrawing': '正在洗牌……',
    'draw.bonusTag': '按时打卡可获三倍经验',
    'draw.revealedHintPre': '骰子已掷下。去',
    'draw.revealedHintLink': '探索',
    'draw.revealedHintPost': '吧。',
    'draw.viewButton': '查看卡片',
    'draw.cooldownLabel': '下次抽取还需',
    'draw.noneLeftTitle': '牌堆已空',
    'draw.noneLeft': '你已经找遍了这个应用知道的布拉格所有地点，没有什么可抽的了。说实话，挺了不起的，也有点让人担心。',
    'draw.alreadyCollected': '✓ 奖励已领取',
    'draw.guestTrialNote': '你现在是以游客身份试玩——这次抽到的地点不会被保存。如果真的想为它收集经验值，请先登录。',
    'detail.bonusApplied': '🎲 盲抽三倍经验奖励！',
    'history.title': '城史时间轴',
    'history.tagline': '从悬崖上的一则预言，到一个国家的诞生——拖动时间轴，看看这些故事究竟发生在哪里。',
    'history.dragHint': '在左侧浏览各个时代，穿越布拉格历史',
    'history.comingSoon': '这个时代还在编写中，敬请期待。',
    'history.relatedLandmarksLabel': '亲自去看看',
  },
  //german
  de: {
    appName: 'Prager Geschichten',
    'nav.explore': 'Erkunden',
    'nav.map': 'Karte',
    'nav.guide': 'Reiseführer',
    'nav.dashboard': 'Dashboard',
    'nav.logout': 'Abmelden',
    'explore.title': 'Erkunde Prag',
    'explore.titleGuest': 'Melde dich an, um Prag zu erkunden!',
    'explore.statsLabel': 'gesammelte Standortkarten',
    'explore.addLocation': '+ Standort hinzufügen',
    'grid.searchPlaceholder': 'Standorte suchen...',
    'grid.filterAll': 'Alle',
    'grid.filterDiscovered': 'Meine Sammlungen',
    'grid.filterLabels': 'Etiketten',
    'grid.filterRarity': 'Seltenheit',
    'grid.clearLabels': 'Löschen',
    'grid.showing': 'anzeigen',
    'grid.noResults': 'Keine Standorte gefunden.',
    'grid.sortDistance': 'Entfernung',
    'grid.sortNewest': 'Neueste',
    'grid.sortRarity': 'Seltenheit',
    'grid.sortCheckin': 'Zuletzt gesammelt',
    'label.historical': 'Historisch',
    'label.modern': 'Modern',
    'label.cultural': 'Kultur & Kunst',
    'label.museum': 'Museum',
    'label.monument': 'Denkmal & Statue',
    'label.communism': 'Kommunismus (Brutalismus)',
    'label.church': 'Kirche & Kathedrale',
    'label.bridge': 'Brücke',
    'label.academy': 'Akademie',
    'label.architecture': 'Architektur',
    'label.landmark': 'Wahrzeichen',
    'label.palace': 'Palast',
    'label.villa': 'Villa',
    'label.basilica': 'Basilika',
    'label.monastery': 'Kloster',
    'label.village-and-town': 'Dorf & Stadt',
    'label.park': 'Park & Garten',
    'label.nature': 'Natur und Landschaft',
    'label.restaurants-and-cafes': 'Restaurants und Cafés',
    'label.cafe': 'Café & Restaurant',
    'label.hidden-gem': 'Verstecktes Juwel',
    'label.square': 'Platz',
    'label.transport': 'Transport',
    'label.tower': 'Turm',
    'label.street': 'Straße & Nachbarschaft',
    'label.municipal': 'Kommunal',
    'label.factory': 'Industrie',
    'label.embassy': 'Botschaft',
    'label.ruin': 'Ruine',
    'label.jewish': 'Jüdisch',
    'label.waterbody': 'Gewässer',
    'label.geology': 'Geografie',
    'label.homestead': 'Gehöft',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    const saved = localStorage.getItem('lang') || 'en';
    document.documentElement.setAttribute('data-lang', saved);
    return saved;
  });
  const [zhVariant, setZhVariant] = useState(() => localStorage.getItem('zhVariant') || 'cn');

  const changeLang = (l) => {
    setLang(l);
    localStorage.setItem('lang', l);
    document.documentElement.setAttribute('data-lang', l);
  };

  const changeZhVariant = (v) => {
    setZhVariant(v);
    localStorage.setItem('zhVariant', v);
  };

  return (
    <LanguageContext.Provider value={{ lang, changeLang, zhVariant, changeZhVariant }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  return useContext(LanguageContext);
}

export function useConvert() {
  const { lang, zhVariant } = useLang();
  return (str) => {
    if (lang === 'zh' && zhVariant === 'tw' && str) return toTW(str);
    return str;
  };
}

export function useT() {
  const { lang, zhVariant } = useLang();
  return (key, vars) => {
    let str = (T[lang] && T[lang][key] !== undefined ? T[lang][key] : T.en[key]) ?? key;
    if (vars) {
      Object.entries(vars).forEach(([k, v]) => {
        str = str.replace('{' + k + '}', v);
      });
    }
    if (lang === 'zh' && zhVariant === 'tw') str = toTW(str);
    return str;
  };
}
