import { createContext, useContext, useState } from 'react';
import * as OpenCC from 'opencc-js';

const TW_OVERRIDES = [
  ['服務器', '伺服器'],
  ['軟件', '軟體'],
  ['地鐵', '捷運'],
];

let _toTW = null;
function toTW(str) {
  if (!_toTW) _toTW = OpenCC.Converter({ from: 'cn', to: 'tw' });
  let result = _toTW(str);
  for (const [from, to] of TW_OVERRIDES) result = result.replaceAll(from, to);
  return result;
}

const T = {
  //english
  en: {
    appName: 'Prague Stories',
    'nav.explore': 'Explore',
    'nav.map': 'Map',
    'nav.guide': 'Guide',
    'nav.dashboard': 'Dashboard',
    'nav.logout': 'Logout',
    'explore.title': 'Explore Prague',
    'explore.titleGuest': 'Login to Explore Prague!',
    'explore.statsLabel': 'location cards collected',
    'explore.addLocation': '+ Add Location',
    'grid.searchPlaceholder': 'Search locations...',
    'grid.filterAll': 'All',
    'grid.filterDiscovered': 'My Collections',
    'grid.filterLabels': 'Labels',
    'grid.filterRarity': 'Rarity',
    'grid.clearLabels': 'Clear',
    'grid.showing': 'showing',
    'grid.noResults': 'No locations found.',
    'grid.sortDistance': 'Distance',
    'grid.sortNewest': 'Newest',
    'grid.sortRarity': 'Top Rarity',
    'grid.sortCheckin': 'Recently Collected',
    'label.historical': 'Historical',
    'label.modern': 'Modern',
    'label.cultural': 'Cultural & Art',
    'label.museum': 'Museum',
    'label.monument': 'Monument & Statue',
    'label.communism': 'Communism (Brutalism)',
    'label.church': 'Church & Cathedral',
    'label.bridge': 'Bridge',
    'label.academy': 'Academy',
    'label.architecture': 'Architecture',
    'label.landmark': 'Landmark',
    'label.palace': 'Palace',
    'label.villa': 'Villa',
    'label.basilica': 'Basilica',
    'label.monastery': 'Monastery',
    'label.village-and-town': 'Village & Town',
    'label.park': 'Park & Garden',
    'label.nature': 'Nature and Landscape',
    'label.restaurants-and-cafes': 'Restaurants and cafes',
    'label.cafe': 'Cafe & Restaurant',
    'label.hidden-gem': 'Hidden Gem',
    'label.square': 'Square',
    'label.transport': 'Transport',
    'label.tower': 'Tower',
    'label.street': 'Street & Neighbourhood',
    'label.municipal': 'Municipal',
    'label.factory': 'Factory',
    'label.embassy': 'Embassy',
    'dashboard.title': 'Explorer Dashboard',
    'dashboard.titleGuest': 'Log in to use the Explorer Dashboard and begin your Prague journey',
    'dashboard.xpToNext': 'XP to next level',
    'dashboard.locations': 'Locations',
    'dashboard.ofPreset': 'of {n} location cards',
    'dashboard.totalVisits': 'collected',
    'dashboard.categoryBreakdown': 'Category Breakdown',
    'dashboard.rarityBreakdown': 'Rarity Breakdown',
    'dashboard.totalXP': 'Total XP',
    'dashboard.achievements': 'Achievements',
    'dashboard.explorerLevels': 'Explorer Levels',
    'dashboard.wakeLockEnable': 'Keep Screen On',
    'dashboard.wakeLockActive': 'Screen Always On',
    'dashboard.wakeLockUnsupported': 'Wake lock not supported on this browser',
    'map.clickMarker': 'Click a marker to explore',
    'map.legend': '● Gold = unlocked  ·  ● Grey = locked',
    'common.loading': 'Loading...',
    'common.visited': '✓ COLLECTED',
    'common.noDesc': 'Description not yet available.',
    'common.wikipedia': '📖 Wikipedia',
    'common.googleMaps': '🗺 Navigate on Google Maps',
    'detail.added': 'Added',
    'detail.at': 'at',
    'proximity.title': '★ Discovery!',
    'proximity.prompt': 'You found {name}! Collect now?',
    'notif.optInTitle': 'Enable location alerts?',
    'notif.optInBody': 'Get notified when you\'re within 100m of an undiscovered location.',
    'notif.optInEnable': 'Enable',
    'common.checkIn': '★ Collect',
    'common.undoVisit': '✕ Uncollect',
    'common.undo': '✕ Undo',
    'common.locked': 'LOCKED',
    'common.cancel': 'Cancel',
    'add.title': 'Add Custom Location',
    'add.name': 'Name',
    'add.labels': 'Labels',
    'add.latitude': 'Latitude',
    'add.longitude': 'Longitude',
    'add.wikiUrl': 'Wikipedia URL (optional)',
    'add.description': 'Description (optional)',
    'add.coverPhoto': 'Cover Photo (optional)',
    'add.coverPhotoHint': 'JPG / PNG / WebP · max 1 MB',
    'add.adding': 'Adding...',
    'auth.login': 'Login',
    'auth.loginSubtitle': 'Welcome back, explorer',
    'auth.register': 'Register',
    'auth.registerSubtitle': 'Prague hides countless secrets. You know zero of them. Unacceptable.',
    'auth.registerFlavor': 'Create thy adventurer profile. The Golden City awaits.',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.username': 'Username',
    'auth.loggingIn': 'Logging in...',
    'auth.enterPrague': '▶ Enter Prague',
    'auth.noAccount': 'No account?',
    'auth.registerHere': 'Register here',
    'auth.creatingAccount': 'Creating account...',
    'auth.startExploring': '▶ Start Exploring',
    'auth.haveAccount': 'Have an account?',
    'auth.loginHere': 'Login here',
    'auth.continueAsGuest': 'Continue without login',
    'auth.loginToCollect': 'Log in to collect',
    'nav.login': 'Login',
  },
  //czech
  cz: {
    appName: 'Pražské Příběhy',
    'nav.explore': 'Průzkum',
    'nav.map': 'Mapa',
    'nav.guide': 'Průvodce',
    'nav.dashboard': 'Přehled',
    'nav.logout': 'Odhlásit',
    'explore.title': 'Prozkoumej Prahu',
    'explore.titleGuest': 'Přihlaste se a prozkoumejte Prahu!',
    'explore.statsLabel': 'míst sesbíráno',
    'explore.addLocation': '+ Přidat Místo',
    'grid.searchPlaceholder': 'Hledat místa...',
    'grid.filterAll': 'Vše',
    'grid.filterDiscovered': 'Moje sbírka',
    'grid.filterLabels': 'Štítky',
    'grid.filterRarity': 'Vzácnost',
    'grid.clearLabels': 'Smazat',
    'grid.showing': 'zobrazeno',
    'grid.noResults': 'Žádná místa nenalezena.',
    'grid.sortDistance': 'Vzdálenost',
    'grid.sortNewest': 'Nejnovější',
    'grid.sortRarity': 'Dle vzácnosti',
    'grid.sortCheckin': 'Naposledy navštíveno',
    'label.historical': 'Historické',
    'label.modern': 'Moderní',
    'label.cultural': 'Kultura & Umění',
    'label.museum': 'Muzeum',
    'label.monument': 'Pomník & Socha',
    'label.communism': 'Komunismus',
    'label.church': 'Kostel',
    'label.bridge': 'Most',
    'label.academy': 'Akademie',
    'label.architecture': 'Architektura',
    'label.landmark': 'Dominanta',
    'label.palace': 'Palác',
    'label.villa': 'Vila',
    'label.basilica': 'Bazilika',
    'label.monastery': 'Klášter',
    'label.village-and-town': 'Vesnice & Město',
    'label.park': 'Park & Zahrada',
    'label.nature': 'Příroda a krajina',
    'label.restaurants-and-cafes': 'Restaurace a kavárny',
    'label.cafe': 'Kavárna',
    'label.hidden-gem': 'Skrytý klenot',
    'label.square': 'Náměstí',
    'label.transport': 'Doprava',
    'label.tower': 'Věž',
    'label.street': 'Ulice & Čtvrť',
    'label.municipal': 'Obecní',
    'label.factory': 'Továrna',
    'label.embassy': 'Velvyslanectví',
    'dashboard.title': 'Průzkumník',
    'dashboard.titleGuest': 'Přihlaste se a odemkněte Průzkumníkův přehled, abyste zahájili cestu Prahou',
    'dashboard.xpToNext': 'XP do další úrovně',
    'dashboard.locations': 'Místa',
    'dashboard.ofPreset': 'z {n} přednastavených',
    'dashboard.totalVisits': 'sesbíráno',
    'dashboard.categoryBreakdown': 'Kategorie',
    'dashboard.rarityBreakdown': 'Vzácnost',
    'dashboard.totalXP': 'Celkem XP',
    'dashboard.achievements': 'Úspěchy',
    'dashboard.explorerLevels': 'Úrovně Průzkumníka',
    'dashboard.wakeLockEnable': 'Ponechat obrazovku zapnutou',
    'dashboard.wakeLockActive': 'Obrazovka stále svítí',
    'dashboard.wakeLockUnsupported': 'Tento prohlížeč nepodporuje blokování uspání',
    'map.clickMarker': 'Klikni na značku pro průzkum',
    'map.legend': '● Zlatá = navštíveno  ·  ● Šedá = zamčeno',
    'common.loading': 'Načítám...',
    'common.visited': '✓ SESBÍRÁNO',
    'common.noDesc': 'Popis zatím není k dispozici.',
    'common.wikipedia': '📖 Wikipedie',
    'common.googleMaps': '🗺 Navigace v Mapách Google',
    'detail.added': 'Přidáno',
    'detail.at': 'dne',
    'proximity.title': '★ Objev!',
    'proximity.prompt': 'Našel jsi {name}! Sbírat nyní?',
    'notif.optInTitle': 'Povolit upozornění na polohu?',
    'notif.optInBody': 'Dostávej upozornění, když jsi do 100 m od neobjeveného místa.',
    'notif.optInEnable': 'Povolit',
    'common.checkIn': '★ Sbírat',
    'common.undoVisit': '✕ Odebrat',
    'common.undo': '✕ Zrušit',
    'common.locked': 'UZAMČENO',
    'common.cancel': 'Zrušit',
    'add.title': 'Přidat vlastní místo',
    'add.name': 'Název',
    'add.labels': 'Štítky',
    'add.latitude': 'Zeměpisná šířka',
    'add.longitude': 'Zeměpisná délka',
    'add.wikiUrl': 'Wikipedia URL (volitelné)',
    'add.description': 'Popis (volitelné)',
    'add.coverPhoto': 'Fotografie (volitelné)',
    'add.coverPhotoHint': 'JPG / PNG / WebP · max 1 MB',
    'add.adding': 'Přidávám...',
    'auth.login': 'Přihlášení',
    'auth.loginSubtitle': 'Vítej zpět, průzkumníku',
    'auth.register': 'Registrace',
    'auth.registerSubtitle': 'Praha ukrývá bezpočet tajemství. Neznáš ani jedno. Nepřijatelné.',
    'auth.registerFlavor': 'Vytvoř si profil dobroduha. Zlaté Město čeká.',
    'auth.email': 'E-mail',
    'auth.password': 'Heslo',
    'auth.username': 'Uživatelské jméno',
    'auth.loggingIn': 'Přihlašuji...',
    'auth.enterPrague': '▶ Vstoupit do Prahy',
    'auth.noAccount': 'Nemáš účet?',
    'auth.registerHere': 'Zaregistruj se',
    'auth.creatingAccount': 'Vytvářím účet...',
    'auth.startExploring': '▶ Začít Prozkoumávat',
    'auth.haveAccount': 'Máš účet?',
    'auth.loginHere': 'Přihlásit se zde',
    'auth.continueAsGuest': 'Pokračovat bez přihlášení',
    'auth.loginToCollect': 'Přihlaste se pro sbírání',
    'nav.login': 'Přihlásit',
  },
  //chinese
  zh: {
    appName: '布拉格故事',
    'nav.explore': '探索',
    'nav.map': '地图',
    'nav.guide': '攻略',
    'nav.dashboard': '仪表盘',
    'nav.logout': '退出',
    'explore.title': '探索布拉格',
    'explore.titleGuest': '登录以探索布拉格！',
    'explore.statsLabel': '个地点卡片已收集',
    'explore.addLocation': '+ 添加地点',
    'grid.searchPlaceholder': '搜索地点...',
    'grid.filterAll': '全部',
    'grid.filterDiscovered': '我的收藏',
    'grid.filterLabels': '标签',
    'grid.filterRarity': '稀有度',
    'grid.clearLabels': '清除',
    'grid.showing': '显示',
    'grid.noResults': '未找到任何地点。',
    'grid.sortDistance': '距离',
    'grid.sortNewest': '最新',
    'grid.sortRarity': '高稀有度',
    'grid.sortCheckin': '最近收藏',
    'label.historical': '历史',
    'label.modern': '现代',
    'label.cultural': '文化与艺术',
    'label.museum': '博物馆',
    'label.monument': '纪念碑与雕像',
    'label.communism': '共产主义',
    'label.church': '教堂',
    'label.bridge': '桥梁',
    'label.academy': '学术',
    'label.architecture': '建筑',
    'label.landmark': '地标',
    'label.palace': '宫殿',
    'label.villa': '别墅',
    'label.basilica': '宗座圣殿',
    'label.monastery': '修道院',
    'label.village-and-town': '村庄与城镇',
    'label.park': '公园与花园',
    'label.nature': '自然与风景',
    'label.restaurants-and-cafes': '餐厅与咖啡馆',
    'label.cafe': '咖啡馆',
    'label.hidden-gem': '隐藏景点',
    'label.square': '广场',
    'label.transport': '交通',
    'label.tower': '塔楼',
    'label.street': '街区',
    'label.municipal': '市政',
    'label.factory': '工厂',
    'label.embassy': '大使馆',
    'dashboard.title': '探索者仪表盘',
    'dashboard.titleGuest': '登录后使用探索者仪表盘，开启你的布拉格之旅',
    'dashboard.xpToNext': 'XP 到下一级',
    'dashboard.locations': '地点',
    'dashboard.ofPreset': '共 {n} 个地点卡片',
    'dashboard.totalVisits': '次收集',
    'dashboard.categoryBreakdown': '分类统计',
    'dashboard.rarityBreakdown': '稀有度统计',
    'dashboard.totalXP': '总经验值',
    'dashboard.achievements': '成就',
    'dashboard.explorerLevels': '探索者等级',
    'dashboard.wakeLockEnable': '保持屏幕常亮',
    'dashboard.wakeLockActive': '屏幕常亮中',
    'dashboard.wakeLockUnsupported': '此浏览器不支持屏幕唤醒锁',
    'map.clickMarker': '点击标记探索地点',
    'map.legend': '● 金色 = 已解锁  ·  ● 灰色 = 已锁定',
    'common.loading': '加载中...',
    'common.visited': '✓ 已收藏',
    'common.noDesc': '暂无描述。',
    'common.wikipedia': '📖 维基百科',
    'common.googleMaps': '🗺 在Google地图上导航',
    'detail.added': '添加',
    'detail.at': '于',
    'proximity.title': '★ 发现！',
    'proximity.prompt': '你发现了{name}！现在收藏？',
    'notif.optInTitle': '启用位置提醒？',
    'notif.optInBody': '当你距离未发现的地点100米内时收到通知。',
    'notif.optInEnable': '启用',
    'common.checkIn': '★ 打卡',
    'common.undoVisit': '✕ 取消收藏？',
    'common.undo': '✕ 撤销',
    'common.locked': '已锁定',
    'common.cancel': '取消',
    'add.title': '添加自定义地点',
    'add.name': '名称',
    'add.labels': '标签',
    'add.latitude': '纬度',
    'add.longitude': '经度',
    'add.wikiUrl': '维基百科 URL（可选）',
    'add.description': '简介（可选）',
    'add.coverPhoto': '封面照片（可选）',
    'add.coverPhotoHint': 'JPG / PNG / WebP · 最大 1 MB',
    'add.adding': '添加中...',
    'auth.login': '登录',
    'auth.loginSubtitle': '欢迎回来，探索者',
    'auth.register': '注册',
    'auth.registerSubtitle': '布拉格藏着无数秘密，你一个都不知道。不可接受。',
    'auth.registerFlavor': '创建你的冒险者档案，黄金之城在等待你。',
    'auth.email': '邮箱',
    'auth.password': '密码',
    'auth.username': '用户名',
    'auth.loggingIn': '登录中...',
    'auth.enterPrague': '▶ 进入布拉格',
    'auth.noAccount': '还没有账号？',
    'auth.registerHere': '立即注册',
    'auth.creatingAccount': '创建账号中...',
    'auth.startExploring': '▶ 开始探索',
    'auth.haveAccount': '已有账号？',
    'auth.loginHere': '立即登录',
    'auth.continueAsGuest': '不登录继续浏览',
    'auth.loginToCollect': '登录后收藏',
    'nav.login': '登录',
  },
  //german
  de: {
    appName: 'Prager Geschichten',
    'nav.explore': 'Erkunden',
    'nav.map': 'Karte',
    'nav.guide': 'Reiseführer',
    'nav.dashboard': 'Dashboard',
    'nav.logout': 'Abmelden',
    'explore.title': 'Erkunde Prag',
    'explore.titleGuest': 'Melde dich an, um Prag zu erkunden!',
    'explore.statsLabel': 'gesammelte Standortkarten',
    'explore.addLocation': '+ Standort hinzufügen',
    'grid.searchPlaceholder': 'Standorte suchen...',
    'grid.filterAll': 'Alle',
    'grid.filterDiscovered': 'Meine Sammlungen',
    'grid.filterLabels': 'Etiketten',
    'grid.filterRarity': 'Seltenheit',
    'grid.clearLabels': 'Löschen',
    'grid.showing': 'anzeigen',
    'grid.noResults': 'Keine Standorte gefunden.',
    'grid.sortDistance': 'Entfernung',
    'grid.sortNewest': 'Neueste',
    'grid.sortRarity': 'Seltenheit',
    'grid.sortCheckin': 'Zuletzt gesammelt',
    'label.historical': 'Historisch',
    'label.modern': 'Modern',
    'label.cultural': 'Kultur & Kunst',
    'label.museum': 'Museum',
    'label.monument': 'Denkmal & Statue',
    'label.communism': 'Kommunismus (Brutalismus)',
    'label.church': 'Kirche & Kathedrale',
    'label.bridge': 'Brücke',
    'label.academy': 'Akademie',
    'label.architecture': 'Architektur',
    'label.landmark': 'Wahrzeichen',
    'label.palace': 'Palast',
    'label.villa': 'Villa',
    'label.basilica': 'Basilika',
    'label.monastery': 'Kloster',
    'label.village-and-town': 'Dorf & Stadt',
    'label.park': 'Park & Garten',
    'label.nature': 'Natur und Landschaft',
    'label.restaurants-and-cafes': 'Restaurants und Cafés',
    'label.cafe': 'Café & Restaurant',
    'label.hidden-gem': 'Verstecktes Juwel',
    'label.square': 'Platz',
    'label.transport': 'Transport',
    'label.tower': 'Turm',
    'label.street': 'Straße & Nachbarschaft',
    'label.municipal': 'Kommunal',
    'label.factory': 'Fabrik',
    'label.embassy': 'Botschaft',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    const saved = localStorage.getItem('lang') || 'en';
    document.documentElement.setAttribute('data-lang', saved);
    return saved;
  });
  const [zhVariant, setZhVariant] = useState(() => localStorage.getItem('zhVariant') || 'cn');

  const changeLang = (l) => {
    setLang(l);
    localStorage.setItem('lang', l);
    document.documentElement.setAttribute('data-lang', l);
  };

  const changeZhVariant = (v) => {
    setZhVariant(v);
    localStorage.setItem('zhVariant', v);
  };

  return (
    <LanguageContext.Provider value={{ lang, changeLang, zhVariant, changeZhVariant }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  return useContext(LanguageContext);
}

export function useConvert() {
  const { lang, zhVariant } = useLang();
  return (str) => {
    if (lang === 'zh' && zhVariant === 'tw' && str) return toTW(str);
    return str;
  };
}

export function useT() {
  const { lang, zhVariant } = useLang();
  return (key, vars) => {
    let str = (T[lang] && T[lang][key] !== undefined ? T[lang][key] : T.en[key]) ?? key;
    if (vars) {
      Object.entries(vars).forEach(([k, v]) => {
        str = str.replace('{' + k + '}', v);
      });
    }
    if (lang === 'zh' && zhVariant === 'tw') str = toTW(str);
    return str;
  };
}
