import { createContext, useContext, useState } from 'react';

const T = {
  en: {
    appName: 'Prague Stories',
    'nav.explore': 'Explore',
    'nav.map': 'Map',
    'nav.guide': 'Guide',
    'nav.dashboard': 'Dashboard',
    'nav.logout': 'Logout',
    'explore.title': 'Explore Prague',
    'explore.statsLabel': 'location cards collected',
    'explore.addLocation': '+ Add Location',
    'grid.searchPlaceholder': 'Search locations...',
    'grid.filterAll': 'All',
    'grid.filterDiscovered': 'My Collections',
    'grid.filterLabels': 'Labels',
    'grid.clearLabels': 'Clear',
    'grid.showing': 'showing',
    'grid.noResults': 'No locations found.',
    'label.historical': 'Historical',
    'label.modern': 'Modern',
    'label.cultural': 'Cultural & Art',
    'label.museum': 'Museum',
    'label.monument': 'Monument & Statue',
    'label.communism': 'Communism (Brutalism)',
    'label.church': 'Church & Cathedral',
    'label.bridge': 'Bridge',
    'label.academy': 'Academy',
    'label.architecture': 'Architecture',
    'label.landmark': 'Landmark',
    'label.palace': 'Palace',
    'label.basilica': 'Basilica',
    'label.monastery': 'Monastery',
    'label.village-and-town': 'Village & Town',
    'label.park': 'Park & Garden',
    'label.nature': 'Nature and Landscape',
    'label.restaurants-and-cafes': 'Restaurants and cafes',
    'label.cafe': 'Cafe & Restaurant',
    'label.hidden-gem': 'Hidden Gem',
    'label.square': 'Square',
    'label.transport': 'Transport',
    'label.tower': 'Tower',
    'label.street': 'Street & Neighbourhood',
    'label.municipal': 'Municipal',
    'dashboard.title': 'Explorer Dashboard',
    'dashboard.xpToNext': 'XP to next level',
    'dashboard.locations': 'Locations',
    'dashboard.ofPreset': 'of {n} preset',
    'dashboard.totalVisits': 'total visits',
    'dashboard.categoryBreakdown': 'Category Breakdown',
    'dashboard.totalXP': 'Total XP',
    'dashboard.achievements': 'Achievements',
    'dashboard.explorerLevels': 'Explorer Levels',
    'map.clickMarker': 'Click a marker to explore',
    'map.legend': '● Gold = unlocked  ·  ● Grey = locked',
    'common.loading': 'Loading...',
    'common.visited': '✓ COLLECTED',
    'common.noDesc': 'Description not yet available.',
    'common.wikipedia': '📖 Wikipedia',
    'common.googleMaps': '🗺 Navigate on Google Maps',
    'proximity.title': '★ Discovery!',
    'proximity.prompt': 'You found {name}! Collect now?',
    'common.checkIn': '★ Collect',
    'common.undoVisit': '✕ Uncollect',
    'common.undo': '✕ Undo',
    'common.locked': 'LOCKED',
    'common.cancel': 'Cancel',
    'add.title': 'Add Custom Location',
    'add.name': 'Name',
    'add.labels': 'Labels',
    'add.latitude': 'Latitude',
    'add.longitude': 'Longitude',
    'add.wikiUrl': 'Wikipedia URL (optional)',
    'add.description': 'Description (optional)',
    'add.coverPhoto': 'Cover Photo (optional)',
    'add.coverPhotoHint': 'JPG / PNG / WebP · max 1 MB',
    'add.adding': 'Adding...',
    'auth.login': 'Login',
    'auth.loginSubtitle': 'Welcome back, explorer',
    'auth.register': 'Register',
    'auth.registerSubtitle': 'Prague hides countless secrets. You know zero of them. Unacceptable.',
    'auth.registerFlavor': 'Create thy adventurer profile. The Golden City awaits.',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.username': 'Username',
    'auth.loggingIn': 'Logging in...',
    'auth.enterPrague': '▶ Enter Prague',
    'auth.noAccount': 'No account?',
    'auth.registerHere': 'Register here',
    'auth.creatingAccount': 'Creating account...',
    'auth.startExploring': '▶ Start Exploring',
    'auth.haveAccount': 'Have an account?',
    'auth.loginHere': 'Login here',
  },
  cz: {
    appName: 'Pražské Příběhy',
    'nav.explore': 'Průzkum',
    'nav.map': 'Mapa',
    'nav.guide': 'Průvodce',
    'nav.dashboard': 'Přehled',
    'nav.logout': 'Odhlásit',
    'explore.title': 'Prozkoumej Prahu',
    'explore.statsLabel': 'míst sesbíráno',
    'explore.addLocation': '+ Přidat Místo',
    'grid.searchPlaceholder': 'Hledat místa...',
    'grid.filterAll': 'Vše',
    'grid.filterDiscovered': 'Moje sbírka',
    'grid.filterLabels': 'Štítky',
    'grid.clearLabels': 'Smazat',
    'grid.showing': 'zobrazeno',
    'grid.noResults': 'Žádná místa nenalezena.',
    'label.historical': 'Historické',
    'label.modern': 'Moderní',
    'label.cultural': 'Kultura & Umění',
    'label.museum': 'Muzeum',
    'label.monument': 'Pomník & Socha',
    'label.communism': 'Komunismus',
    'label.church': 'Kostel',
    'label.bridge': 'Most',
    'label.academy': 'Akademie',
    'label.architecture': 'Architektura',
    'label.landmark': 'Dominanta',
    'label.palace': 'Palác',
    'label.basilica': 'Bazilika',
    'label.monastery': 'Klášter',
    'label.village-and-town': 'Vesnice & Město',
    'label.park': 'Park & Zahrada',
    'label.nature': 'Příroda a krajina',
    'label.restaurants-and-cafes': 'Restaurace a kavárny',
    'label.cafe': 'Kavárna',
    'label.hidden-gem': 'Skrytý klenot',
    'label.square': 'Náměstí',
    'label.transport': 'Doprava',
    'label.tower': 'Věž',
    'label.street': 'Ulice & Čtvrť',
    'label.municipal': 'Obecní',
    'dashboard.title': 'Průzkumník',
    'dashboard.xpToNext': 'XP do další úrovně',
    'dashboard.locations': 'Místa',
    'dashboard.ofPreset': 'z {n} přednastavených',
    'dashboard.totalVisits': 'návštěv celkem',
    'dashboard.categoryBreakdown': 'Kategorie',
    'dashboard.totalXP': 'Celkem XP',
    'dashboard.achievements': 'Úspěchy',
    'dashboard.explorerLevels': 'Úrovně Průzkumníka',
    'map.clickMarker': 'Klikni na značku pro průzkum',
    'map.legend': '● Zlatá = navštíveno  ·  ● Šedá = zamčeno',
    'common.loading': 'Načítám...',
    'common.visited': '✓ SESBÍRÁNO',
    'common.noDesc': 'Popis zatím není k dispozici.',
    'common.wikipedia': '📖 Wikipedie',
    'common.googleMaps': '🗺 Navigace v Mapách Google',
    'proximity.title': '★ Objev!',
    'proximity.prompt': 'Našel jsi {name}! Sbírat nyní?',
    'common.checkIn': '★ Sbírat',
    'common.undoVisit': '✕ Odebrat',
    'common.undo': '✕ Zrušit',
    'common.locked': 'UZAMČENO',
    'common.cancel': 'Zrušit',
    'add.title': 'Přidat vlastní místo',
    'add.name': 'Název',
    'add.labels': 'Štítky',
    'add.latitude': 'Zeměpisná šířka',
    'add.longitude': 'Zeměpisná délka',
    'add.wikiUrl': 'Wikipedia URL (volitelné)',
    'add.description': 'Popis (volitelné)',
    'add.coverPhoto': 'Fotografie (volitelné)',
    'add.coverPhotoHint': 'JPG / PNG / WebP · max 1 MB',
    'add.adding': 'Přidávám...',
    'auth.login': 'Přihlášení',
    'auth.loginSubtitle': 'Vítej zpět, průzkumníku',
    'auth.register': 'Registrace',
    'auth.registerSubtitle': 'Praha ukrývá bezpočet tajemství. Neznáš ani jedno. Nepřijatelné.',
    'auth.registerFlavor': 'Vytvoř si profil dobroduha. Zlaté Město čeká.',
    'auth.email': 'E-mail',
    'auth.password': 'Heslo',
    'auth.username': 'Uživatelské jméno',
    'auth.loggingIn': 'Přihlašuji...',
    'auth.enterPrague': '▶ Vstoupit do Prahy',
    'auth.noAccount': 'Nemáš účet?',
    'auth.registerHere': 'Zaregistruj se',
    'auth.creatingAccount': 'Vytvářím účet...',
    'auth.startExploring': '▶ Začít Prozkoumávat',
    'auth.haveAccount': 'Máš účet?',
    'auth.loginHere': 'Přihlásit se zde',
  },
  zh: {
    appName: '布拉格故事',
    'nav.explore': '探索',
    'nav.map': '地图',
    'nav.guide': '攻略',
    'nav.dashboard': '仪表盘',
    'nav.logout': '退出',
    'explore.title': '探索布拉格',
    'explore.statsLabel': '个地点卡片已收集',
    'explore.addLocation': '+ 添加地点',
    'grid.searchPlaceholder': '搜索地点...',
    'grid.filterAll': '全部',
    'grid.filterDiscovered': '我的收藏',
    'grid.filterLabels': '标签',
    'grid.clearLabels': '清除',
    'grid.showing': '显示',
    'grid.noResults': '未找到任何地点。',
    'label.historical': '历史',
    'label.modern': '现代',
    'label.cultural': '文化与艺术',
    'label.museum': '博物馆',
    'label.monument': '纪念碑与雕像',
    'label.communism': '共产主义',
    'label.church': '教堂',
    'label.bridge': '桥梁',
    'label.academy': '学术',
    'label.architecture': '建筑',
    'label.landmark': '地标',
    'label.palace': '宫殿',
    'label.basilica': '宗座圣殿',
    'label.monastery': '修道院',
    'label.village-and-town': '村庄与城镇',
    'label.park': '公园与花园',
    'label.nature': '自然与风景',
    'label.restaurants-and-cafes': '餐厅与咖啡馆',
    'label.cafe': '咖啡馆',
    'label.hidden-gem': '隐藏景点',
    'label.square': '广场',
    'label.transport': '交通',
    'label.tower': '塔楼',
    'label.street': '街区',
    'label.municipal': '市政',
    'dashboard.title': '探索者仪表盘',
    'dashboard.xpToNext': 'XP 到下一级',
    'dashboard.locations': '地点',
    'dashboard.ofPreset': '共 {n} 个预设',
    'dashboard.totalVisits': '总访问次数',
    'dashboard.categoryBreakdown': '分类统计',
    'dashboard.totalXP': '总经验值',
    'dashboard.achievements': '成就',
    'dashboard.explorerLevels': '探索者等级',
    'map.clickMarker': '点击标记探索地点',
    'map.legend': '● 金色 = 已解锁  ·  ● 灰色 = 已锁定',
    'common.loading': '加载中...',
    'common.visited': '✓ 已收藏',
    'common.noDesc': '暂无描述。',
    'common.wikipedia': '📖 维基百科',
    'common.googleMaps': '🗺 在Google地图上导航',
    'proximity.title': '★ 发现！',
    'proximity.prompt': '你发现了{name}！现在收藏？',
    'common.checkIn': '★ 打卡',
    'common.undoVisit': '✕ 取消收藏？',
    'common.undo': '✕ 撤销',
    'common.locked': '已锁定',
    'common.cancel': '取消',
    'add.title': '添加自定义地点',
    'add.name': '名称',
    'add.labels': '标签',
    'add.latitude': '纬度',
    'add.longitude': '经度',
    'add.wikiUrl': '维基百科 URL（可选）',
    'add.description': '简介（可选）',
    'add.coverPhoto': '封面照片（可选）',
    'add.coverPhotoHint': 'JPG / PNG / WebP · 最大 1 MB',
    'add.adding': '添加中...',
    'auth.login': '登录',
    'auth.loginSubtitle': '欢迎回来，探索者',
    'auth.register': '注册',
    'auth.registerSubtitle': '布拉格藏着无数秘密，你一个都不知道。不可接受。',
    'auth.registerFlavor': '创建你的冒险者档案，黄金之城在等待你。',
    'auth.email': '邮箱',
    'auth.password': '密码',
    'auth.username': '用户名',
    'auth.loggingIn': '登录中...',
    'auth.enterPrague': '▶ 进入布拉格',
    'auth.noAccount': '还没有账号？',
    'auth.registerHere': '立即注册',
    'auth.creatingAccount': '创建账号中...',
    'auth.startExploring': '▶ 开始探索',
    'auth.haveAccount': '已有账号？',
    'auth.loginHere': '立即登录',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    const saved = localStorage.getItem('lang') || 'en';
    document.documentElement.setAttribute('data-lang', saved);
    return saved;
  });

  const changeLang = (l) => {
    setLang(l);
    localStorage.setItem('lang', l);
    document.documentElement.setAttribute('data-lang', l);
  };

  return (
    <LanguageContext.Provider value={{ lang, changeLang }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  return useContext(LanguageContext);
}

export function useT() {
  const { lang } = useLang();
  return (key, vars) => {
    let str = (T[lang] && T[lang][key] !== undefined ? T[lang][key] : T.en[key]) ?? key;
    if (vars) {
      Object.entries(vars).forEach(([k, v]) => {
        str = str.replace('{' + k + '}', v);
      });
    }
    return str;
  };
}
