const map = {
  // Religious
  castle: "🏰",
  bridge: "🌉",
  square: "🏛️",
  clock: "🕰️",
  cathedral: "⛪",
  fortress: "🗼",
  synagogue: "✡️",
  cemetery: "🪦",
  church: "⛪",
  chapel: "🛕",
  tower: "🗼",
  artnouveau: "🏛️",
  townhall: "🏛️",
  "gothic-church": "⛪",
  district: "🏘️",
  palace: "🏯",
  palace2: "🏯",
  monastery: "🏯",
  newtown: "🏙️",
  boulevard: "🛤️",
  curiosity: "🔮",
  cemetery2: "🪦",
  library: "📚",
  basilica: "⛪",
  "prison-tower": "⛓️",
  "royal-hall": "🏛️",
  alley: "🪨",
  synagogue2: "✡️",
  "baroque-church": "⛪",
  chapel2: "🛕",
  // Cultural
  museum: "🏛️",
  kafka: "📖",
  artnouveau2: "🎨",
  theatre: "🎭",
  "contemporary-art": "🖼️",
  "concert-hall": "🎵",
  "music-museum": "🎻",
  gallery: "🖼️",
  stage: "🎭",
  propaganda: "📋",
  "city-gallery": "🖼️",
  opera: "🎭",
  estates: "🎭",
  anthropology: "🗿",
  "tech-museum": "⚙️",
  "kafka-statue": "🗿",
  memorial: "🪦",
  planetarium: "🔭",
  "city-museum": "🏛️",
  smetana: "🎼",
  // Natural
  park: "🌳",
  valley: "🏞️",
  garden: "🌸",
  "hilltop-park": "⛰️",
  ravine: "🏔️",
  forest: "🌲",
  hill: "⛰️",
  river: "🌊",
  "vineyard-park": "🍇",
  island: "🏝️",
  ponds: "💧",
  hilltop: "⛰️",
  "chateau-garden": "🌹",
  "deep-forest": "🌲",
  "rose-garden": "🌹",
  // Food & Entertainment
  pub: "🍺",
  "food-market": "🍔",
  "grand-cafe": "☕",
  brewery: "🍺",
  market: "🛒",
  cafe: "☕",
  "garden-pub": "🍺",
  butcher: "🥩",
  "modern-czech": "🍽️",
  festival: "🎪",
  "pilsner-pub": "🍺",
  "local-market": "🛒",
  patisserie: "🧁",
  "craft-brewery": "🍺",
  "covered-market": "🛒",
  "vietnamese-market": "🍜",
  // Hidden gems
  "tv-tower": "📡",
  "street-art": "🎨",
  graffiti: "🎨",
  canal: "🌊",
  "secret-garden": "🌿",
  "mystery-church": "🕯️",
  "rotating-head": "🔮",
  vineyard: "🍇",
  viewpoint: "👁️",
  "lennon-wall": "✌️",
  "cobblestone-lane": "🪨",
  brutalist: "🏢",
  // Entertainment
  zoo: "🦁",
  club: "🎧",
  "escape-room": "🔐",
  "eiffel-mini": "🗼",
  "mirror-maze": "🪞",
  waterpark: "💦",
  boat: "⛵",
  "island-stage": "🎪",
};

export const LABEL_DEFINITIONS = {
  historical: { emoji: "🏛️", en: "Historical", cz: "Historické", zh: "历史" },
  modern: { emoji: "🏙️", en: "Modern", cz: "Moderní", zh: "现代" },
  cultural: {
    emoji: "🎭",
    en: "Cultural & Art",
    cz: "Kultura & Umění",
    zh: "文化与艺术",
  },
  museum: { emoji: "🏛️", en: "Museum", cz: "Muzeum", zh: "博物馆" },
  monument: {
    emoji: "🗿",
    en: "Monument & Statue",
    cz: "Pomník & Socha",
    zh: "纪念碑与雕像",
  },
  communism: {
    emoji: "☭",
    en: "Communism and Cold War",
    cz: "Komunismus",
    zh: "共产主义与冷战",
  },
  church: { emoji: "⛪", en: "Church & Cathedral", cz: "Kostel", zh: "教堂" },
  bridge: { emoji: "🌉", en: "Bridge", cz: "Most", zh: "桥梁" },
  academy: { emoji: "📚", en: "Academy", cz: "Akademie", zh: "学术" },
  architecture: {
    emoji: "🏛️",
    en: "Architecture",
    cz: "Architektura",
    zh: "建筑",
  },
  landmark: { emoji: "📍", en: "Landmark", cz: "Dominanta", zh: "地标" },
  palace: { emoji: "🏯", en: "Palace", cz: "Palác", zh: "宫殿" },
  villa: { emoji: "🏡", en: "Villa", cz: "Vila", zh: "别墅" },
  basilica: { emoji: "⛪", en: "Basilica", cz: "Bazilika", zh: "宗座圣殿" },
  monastery: { emoji: "🏯", en: "Monastery", cz: "Klášter", zh: "修道院" },
  park: {
    emoji: "🌳",
    en: "Park & Garden",
    cz: "Park & Zahrada",
    zh: "公园与花园",
  },
  nature: { emoji: "🌿", en: "Nature and Landscape", cz: "Příroda a krajina", zh: "自然与风景" },
  "village-and-town": { emoji: "🏘️", en: "Village & Town", cz: "Vesnice & Město", zh: "村庄与城镇" },
  "restaurants-and-cafes": {
    emoji: "🍽️",
    en: "Restaurants and cafes",
    cz: "Restaurace a kavárny",
    zh: "餐厅与咖啡馆",
  },
  cafe: { emoji: "☕", en: "Entertainment and Leisure", cz: "Zábava", zh: "休闲娱乐" },
  "hidden-gem": {
    emoji: "💎",
    en: "Hidden Gem",
    cz: "Skrytý klenot",
    zh: "小众景点",
  },
  square: { emoji: "⛲", en: "Square", cz: "Náměstí", zh: "广场" },
  transport: { emoji: "🚉", en: "Transport", cz: "Doprava", zh: "交通" },
  tower: { emoji: "🗼", en: "Tower", cz: "Věž", zh: "塔楼" },
  street: {
    emoji: "🏘️",
    en: "Street & Neighbourhood",
    cz: "Ulice & Čtvrť",
    zh: "街区",
  },
  municipal: { emoji: "🏢", en: "Municipal", cz: "Obecní", zh: "市政" },
  factory: { emoji: "🏭", en: "Factory", cz: "Továrna", zh: "工厂" },
  embassy: { emoji: "🎌", en: "Embassy", cz: "Velvyslanectví", zh: "大使馆" },
  "castle and fortress": {
    emoji: "🏰",
    en: "Castle & Fortress",
    cz: "Hrad & Pevnost",
    zh: "城堡与要塞",
  },
};

export const LABEL_COLORS = {
  historical: "#7a5210",
  modern: "#1a3a5a",
  cultural: "#5a1480",
  museum: "#2a1a50",
  monument: "#3a2a50",
  communism: "#6a0a0a",
  church: "#7a4a10",
  bridge: "#1a4a6a",
  academy: "#0a5050",
  architecture: "#4a3a6a",
  landmark: "#8a3f3f",
  palace: "#5a2a1a",
  villa: "#6a4a2a",
  basilica: "#7a4a10",
  monastery: "#5a2a1a",
  "village-and-town": "#3b7a5a",
  park: "#145a20",
  nature: "#2f7d32",
  "restaurants-and-cafes": "#7a4e1d",
  cafe: "#5a3a00",
  "hidden-gem": "#0a3a7a",
  square: "#1a4a4a",
  transport: "#2a2a4a",
  tower: "#3a3a3a",
  street: "#4a3020",
  municipal: "#2a4a2a",
  factory: "#5a5a3a",
  embassy: "#2a5a7a",
  "castle and fortress": "#5a2a1a",
};

export function getArt(pixelArtKey, labels) {
  const firstLabel = Array.isArray(labels) ? labels[0] : labels;
  return map[pixelArtKey] || LABEL_DEFINITIONS[firstLabel]?.emoji || "📍";
}

// Legacy alias kept for any remaining references
export const CATEGORY_LABELS = Object.fromEntries(
  Object.entries(LABEL_DEFINITIONS).map(([k, v]) => [k, `${v.emoji} ${v.en}`]),
);
